[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.14.0"

[dev-dependencies]
solana-program-test = "1.14.0"
solana-sdk = "1.14.0"

[lib]
crate-type = ["cdylib", "lib"]